<?php

namespace App\Services;

// Cafe data repository providing realistic mock data ready for Eloquent models
class CafeRepository
{
    // Return all available cafes
    public static function all(): array
    {
        return [
            [
                'id' => 1,
                'slug' => 'the-velvet-bean',
                'name' => 'The Velvet Bean',
                'tagline' => 'Artisanal roastery & tranquil sanctuary',
                'location' => 'Colombo 07',
                'address' => '42 Horton Place, Cinnamon Gardens, Colombo 07',
                'rating' => 4.8,
                'reviews_count' => 320,
                'verified' => true,
                'price_level' => '$$$',
                'average_price' => 'LKR 1,200 - 2,500',
                'distance' => '1.2 km',
                'availability_status' => 'Available today',
                'availability_badge' => 'Available',
                'tables_left' => 4,
                'is_favourite' => true,
                'cafe_type' => 'Specialty Coffee',
                'tags' => ['Specialty Coffee', 'Brunch', 'Desserts', 'Rooftop', 'Work Friendly'],
                'short_description' => 'Sunlit courtyards, freshly roasted Ethiopian beans, and handcrafted sourdough brunches in the heart of Colombo.',
                'about' => 'The Velvet Bean is a heritage-inspired coffee house and micro-roastery nestled amidst lush tropical foliage. Designed as an unhurried sanctuary for coffee lovers, remote creators, and intimate conversation, our baristas pull espresso from single-origin beans roasted in-house every morning.',
                'image' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80',
                ],
                'opening_hours' => [
                    'Monday - Friday' => '7:30 AM - 10:00 PM',
                    'Saturday - Sunday' => '8:00 AM - 11:00 PM',
                ],
                'amenities' => [
                    'Ultra-fast Wi-Fi',
                    'Dedicated Quiet Zone',
                    'Power Outlets at every booth',
                    'Outdoor Garden Terrace',
                    'Pet Friendly Courtyard',
                    'Specialty Pour-Over Bar',
                    'Valet & Free Street Parking',
                ],
                'cuisine' => 'Specialty Coffee, Artisanal Pastries & European Brunch',
                'reservation_fee' => 500, // Dynamic fee configured by cafe
                'cancellation_window_hours' => 2,
                'cancellation_penalty_percentage' => 50,
                'cancellation_policy' => 'Cancellations up to 2 hours before your booking receive a 100% refund. Cancellations within 2 hours are subject to a 50% cancellation fee.',
            ],
            [
                'id' => 2,
                'slug' => 'brew-and-beyond',
                'name' => 'Brew & Beyond',
                'tagline' => 'Panoramic misty hillside coffee atelier',
                'location' => 'Kandy',
                'address' => '18 Bahirawakanda Hill, Kandy',
                'rating' => 4.6,
                'reviews_count' => 195,
                'verified' => true,
                'price_level' => '$$',
                'average_price' => 'LKR 950 - 1,800',
                'distance' => '2.5 km',
                'availability_status' => 'Available today',
                'availability_badge' => 'Available',
                'tables_left' => 3,
                'is_favourite' => true,
                'cafe_type' => 'Coffee & Desserts',
                'tags' => ['Coffee', 'Desserts', 'Hill View', 'Cozy'],
                'short_description' => 'Slow-drip single origin coffees overlooking the misty Kandy hills and vintage wooden deck seating.',
                'about' => 'Perched on the green slopes of Kandy, Brew & Beyond marries Ceylon hill-country Arabica beans with slow-brew methods. Cozy timber architecture with panoramic valley vistas.',
                'image' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
                ],
                'opening_hours' => [
                    'Daily' => '8:00 AM - 9:30 PM',
                ],
                'amenities' => [
                    'Scenic Balcony',
                    'High-speed Wi-Fi',
                    'Handmade Tarts & Cakes',
                    'Card & Cash Payments',
                ],
                'cuisine' => 'Ceylon Artisanal Coffee & French Desserts',
                'reservation_fee' => 400,
                'cancellation_window_hours' => 3,
                'cancellation_penalty_percentage' => 50,
                'cancellation_policy' => 'A 50% cancellation fee may apply to the reservation deposit. The remaining eligible amount will be refunded according to the cancellation policy.',
            ],
            [
                'id' => 3,
                'slug' => 'sunrise-roasters',
                'name' => 'Sunrise Roasters',
                'tagline' => 'Ocean breeze & golden morning roasts',
                'location' => 'Galle',
                'address' => '29 Church Street, Galle Fort, Galle',
                'rating' => 4.9,
                'reviews_count' => 412,
                'verified' => true,
                'price_level' => '$$$',
                'average_price' => 'LKR 1,100 - 2,200',
                'distance' => '0.8 km',
                'availability_status' => 'Available today',
                'availability_badge' => 'Available',
                'tables_left' => 2,
                'is_favourite' => true,
                'cafe_type' => 'Specialty Coffee',
                'tags' => ['Specialty Coffee', 'Seaview', 'Galle Fort', 'Brunch'],
                'short_description' => 'Colonial Dutch verandah cafe serving cold brew tonics, brioche French toast, and ocean views.',
                'about' => 'Housed in a preserved 18th-century Dutch colonial villa within the UNESCO World Heritage Galle Fort, Sunrise Roasters has earned acclaim for small-batch roasting and soothing seaside mornings.',
                'image' => 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=800&q=80',
                    'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80',
                ],
                'opening_hours' => [
                    'Daily' => '7:00 AM - 8:00 PM',
                ],
                'amenities' => [
                    'Historic Verandah',
                    'Sea Breeze Seating',
                    'Specialty Cold Brews',
                    'Artisanal Sourdough',
                ],
                'cuisine' => 'Coastal Brunch & Artisan Espresso',
                'reservation_fee' => 600,
                'cancellation_window_hours' => 4,
                'cancellation_penalty_percentage' => 50,
                'cancellation_policy' => 'Cancel at least 4 hours ahead for full refund. 50% late cancellation fee applies within 4 hours.',
            ],
            [
                'id' => 4,
                'slug' => 'the-daily-grind',
                'name' => 'The Daily Grind',
                'tagline' => 'Urban retreat with booklined nooks',
                'location' => 'Colombo 03',
                'address' => '88 Galle Road, Kollupitiya, Colombo 03',
                'rating' => 4.4,
                'reviews_count' => 120,
                'verified' => false,
                'price_level' => '$$',
                'average_price' => 'LKR 800 - 1,600',
                'distance' => '3.1 km',
                'availability_status' => 'Available today',
                'availability_badge' => 'Available',
                'tables_left' => 6,
                'is_favourite' => true,
                'cafe_type' => 'Coffee & Brunch',
                'tags' => ['Coffee', 'Work Friendly', 'Books', 'Bakery'],
                'short_description' => 'Comfortable armchairs, curated bookshelves, and aromatic pour-overs for relaxed afternoon work sessions.',
                'about' => 'A cozy bibliophile cafe with vintage timber tables and mellow jazz. Ideal for focused work, reading, and savoring freshly pulled Flat Whites.',
                'image' => 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=800&q=80',
                ],
                'opening_hours' => [
                    'Daily' => '8:00 AM - 10:30 PM',
                ],
                'amenities' => [
                    'Quiet Library Lounge',
                    'High-speed Wi-Fi',
                    'Plentiful Power Sockets',
                    'Filter Coffee Bar',
                ],
                'cuisine' => 'Specialty Espresso, Bagels & Gourmet Cookies',
                'reservation_fee' => 350,
                'cancellation_window_hours' => 2,
                'cancellation_penalty_percentage' => 30,
                'cancellation_policy' => 'Full refund up to 2 hours before booking. 30% fee applies afterwards.',
            ],
            [
                'id' => 5,
                'slug' => 'bean-theory',
                'name' => 'Bean Theory',
                'tagline' => 'Scientific precision meets botanical warmth',
                'location' => 'Nugegoda',
                'address' => '14 Nawala Road, Nugegoda',
                'rating' => 4.7,
                'reviews_count' => 280,
                'verified' => true,
                'price_level' => '$$',
                'average_price' => 'LKR 900 - 1,900',
                'distance' => '4.8 km',
                'availability_status' => 'Almost full',
                'availability_badge' => 'Almost full',
                'tables_left' => 1,
                'is_favourite' => false,
                'cafe_type' => 'Brunch & Desserts',
                'tags' => ['Brunch', 'Desserts', 'Garden Patio', 'Botanical'],
                'short_description' => 'Glasshouse cafe filled with indoor ferns, nitrogen-infused cold brews, and strawberry waffles.',
                'about' => 'Part greenhouse, part modern laboratory. Bean Theory crafts experimental brews paired with savory brioche burgers and signature Basque cheesecakes.',
                'image' => 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=800&q=80',
                ],
                'opening_hours' => [
                    'Daily' => '8:30 AM - 11:00 PM',
                ],
                'amenities' => [
                    'Glasshouse Seating',
                    'Outdoor Garden',
                    'Nitro Cold Brew Tap',
                    'Wheelchair Accessible',
                ],
                'cuisine' => 'Modern Fusion Brunch & Artisan Sweets',
                'reservation_fee' => 450,
                'cancellation_window_hours' => 2,
                'cancellation_penalty_percentage' => 50,
                'cancellation_policy' => 'Cancel with 2+ hours notice for 100% refund. 50% fee applies for late cancellations.',
            ],
            [
                'id' => 6,
                'slug' => 'urban-sip',
                'name' => 'Urban Sip',
                'tagline' => 'Warm concrete, brass accents & lively buzz',
                'location' => 'Colombo 05',
                'address' => '54 Havelock Road, Colombo 05',
                'rating' => 4.5,
                'reviews_count' => 90,
                'verified' => true,
                'price_level' => '$$',
                'average_price' => 'LKR 850 - 1,750',
                'distance' => '2.1 km',
                'availability_status' => 'Available today',
                'availability_badge' => 'Available',
                'tables_left' => 5,
                'is_favourite' => false,
                'cafe_type' => 'Coffee & Bistro',
                'tags' => ['Coffee', 'Pet Friendly', 'Terrace', 'Social'],
                'short_description' => 'Pet-friendly sun deck with cold press juices, specialty matcha lattes, and classic avocado toasts.',
                'about' => 'A lively urban space beloved by weekend dog walkers and breakfast enthusiasts. Vibrant terrace, open air coffee station, and welcoming staff.',
                'image' => 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80',
                'gallery' => [
                    'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=800&q=80',
                ],
                'opening_hours' => [
                    'Daily' => '7:30 AM - 9:00 PM',
                ],
                'amenities' => [
                    'Pet Friendly Deck',
                    'High-speed Wi-Fi',
                    'Outdoor Garden',
                    'Takeaway Window',
                ],
                'cuisine' => 'All-Day Breakfast & Specialty Teas',
                'reservation_fee' => 300,
                'cancellation_window_hours' => 2,
                'cancellation_penalty_percentage' => 25,
                'cancellation_policy' => 'Full refund up to 2 hours prior to reservation. 25% fee applies for late cancellations.',
            ],
        ];
    }

    // Find a cafe by its slug
    public static function findBySlug(string $slug): ?array
    {
        foreach (self::all() as $cafe) {
            if ($cafe['slug'] === $slug) {
                return $cafe;
            }
        }

        return null;
    }

    // Get tables for a cafe
    public static function getTablesForCafe(string $slug): array
    {
        return [
            [
                'id' => 1,
                'name' => 'Table 1',
                'capacity' => '2 - 4 guests',
                'type' => 'Indoor Cozy Booth',
                'location' => 'Indoor',
                'category' => 'indoor',
                'status' => 'available',
                'status_label' => 'Available',
                'description' => 'Leather padded banquet booth near the warm brick fireplace.',
                'image' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80',
            ],
            [
                'id' => 2,
                'name' => 'Table 2',
                'capacity' => '2 - 4 guests',
                'type' => 'Window Seat',
                'location' => 'Indoor',
                'category' => 'window',
                'status' => 'available',
                'status_label' => 'Available',
                'description' => 'Bright sunlit table next to heritage arched windows looking out to lush tropical garden.',
                'image' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&q=80',
            ],
            [
                'id' => 3,
                'name' => 'Table 3',
                'capacity' => '4 - 6 guests',
                'type' => 'Rooftop Lounge',
                'location' => 'Rooftop',
                'category' => 'rooftop',
                'status' => 'available',
                'status_label' => 'Available',
                'description' => 'Spacious open-air teak table with panoramic canopy view.',
                'image' => 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=600&q=80',
            ],
            [
                'id' => 4,
                'name' => 'Table 4',
                'capacity' => '2 - 4 guests',
                'type' => 'Outdoor Courtyard',
                'location' => 'Outdoor',
                'category' => 'outdoor',
                'status' => 'available',
                'status_label' => 'Available',
                'description' => 'Shaded wrought-iron table beneath creeping bougainvillea trees.',
                'image' => 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=600&q=80',
            ],
            [
                'id' => 5,
                'name' => 'Table 5',
                'capacity' => '2 guests',
                'type' => 'Quiet Corner',
                'location' => 'Indoor',
                'category' => 'indoor',
                'status' => 'almost_full',
                'status_label' => 'Almost full',
                'description' => 'Intimate wooden nook equipped with dual power sockets for quiet focus.',
                'image' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
            ],
        ];
    }

    // Get food menu items for a cafe
    public static function getMenuForCafe(string $slug): array
    {
        return [
            [
                'id' => 101,
                'name' => 'Cappuccino',
                'category' => 'Coffee',
                'price' => 750,
                'formatted_price' => 'LKR 750',
                'description' => 'Velvety micro-foamed local milk over a double shot of house espresso blend.',
                'image' => 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=500&q=80',
            ],
            [
                'id' => 102,
                'name' => 'Iced Caramel Latte',
                'category' => 'Coffee',
                'price' => 850,
                'formatted_price' => 'LKR 850',
                'description' => 'Cold milk, double espresso, handcrafted salted caramel drizzle over crystal ice.',
                'image' => 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=500&q=80',
            ],
            [
                'id' => 103,
                'name' => 'Avocado Toast',
                'category' => 'Breakfast',
                'price' => 1250,
                'formatted_price' => 'LKR 1,250',
                'description' => 'Crushed Hass avocado on toasted country sourdough, poached eggs, feta crumbs, chili flakes.',
                'image' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=500&q=80',
            ],
            [
                'id' => 104,
                'name' => 'Pancake Stack',
                'category' => 'Breakfast',
                'price' => 1400,
                'formatted_price' => 'LKR 1,400',
                'description' => 'Fluffy buttermilk hotcakes layered with whipped vanilla butter, maple drizzle and berries.',
                'image' => 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=500&q=80',
            ],
            [
                'id' => 105,
                'name' => 'Classic Burger',
                'category' => 'Main Course',
                'price' => 1650,
                'formatted_price' => 'LKR 1,650',
                'description' => 'Seared prime beef patty, melted cheddar, crisp lettuce, house relish on brioche bun.',
                'image' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=80',
            ],
            [
                'id' => 106,
                'name' => 'Chocolate Cake',
                'category' => 'Desserts',
                'price' => 950,
                'formatted_price' => 'LKR 950',
                'description' => 'Decadent dark chocolate ganache layered sponge with Madagascar vanilla bean chantilly.',
                'image' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=500&q=80',
            ],
            [
                'id' => 107,
                'name' => 'Matcha Cold Foam',
                'category' => 'Drinks',
                'price' => 890,
                'formatted_price' => 'LKR 890',
                'description' => 'Uji ceremonial matcha layered with sweetened oat milk and creamy vanilla cloud foam.',
                'image' => 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=500&q=80',
            ],
            [
                'id' => 108,
                'name' => 'French Croissant',
                'category' => 'Breakfast',
                'price' => 600,
                'formatted_price' => 'LKR 600',
                'description' => 'Flaky 27-layer butter croissant baked golden each morning.',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=500&q=80',
            ],
        ];
    }

    // Get sample customer reservations
    public static function getCustomerReservations(): array
    {
        return [
            [
                'id' => 'RES-2026-891',
                'cafe_slug' => 'the-velvet-bean',
                'cafe_name' => 'The Velvet Bean',
                'cafe_location' => 'Colombo 07',
                'cafe_image' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=400&q=80',
                'date' => 'Tomorrow, Oct 5, 2026',
                'time' => '10:30 AM',
                'guests' => 2,
                'table_name' => 'Table 2',
                'table_type' => 'Window Seat',
                'table_location' => 'Indoor',
                'status' => 'confirmed',
                'status_label' => 'Confirmed',
                'payment_status' => 'Paid',
                'reservation_fee' => 500,
                'paid_amount' => 500,
                'remaining_balance' => 0,
                'cancellation_policy' => 'A 50% cancellation fee will be deducted upon cancellation. The remaining balance will be refunded.',
                'cancellation_allowed' => true,
            ],
            [
                'id' => 'RES-2026-892',
                'cafe_slug' => 'brew-and-beyond',
                'cafe_name' => 'Brew & Beyond',
                'cafe_location' => 'Kandy',
                'cafe_image' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=400&q=80',
                'date' => 'Wed, Oct 8, 2026',
                'time' => '2:00 PM',
                'guests' => 4,
                'table_name' => 'Table 5',
                'table_type' => 'Hill View Deck',
                'table_location' => 'Outdoor',
                'status' => 'confirmed',
                'status_label' => 'Confirmed',
                'payment_status' => 'Paid',
                'reservation_fee' => 400,
                'paid_amount' => 400,
                'remaining_balance' => 0,
                'cancellation_policy' => 'A 50% cancellation fee will be deducted upon cancellation. The remaining balance will be refunded.',
                'cancellation_allowed' => true,
            ],
            [
                'id' => 'RES-2026-893',
                'cafe_slug' => 'sunrise-roasters',
                'cafe_name' => 'Sunrise Roasters',
                'cafe_location' => 'Galle',
                'cafe_image' => 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=400&q=80',
                'date' => 'Sun, Oct 12, 2026',
                'time' => '11:00 AM',
                'guests' => 2,
                'table_name' => 'Table 1',
                'table_type' => 'Verandah Seat',
                'table_location' => 'Outdoor',
                'status' => 'pending',
                'status_label' => 'Pending Confirmation',
                'payment_status' => 'Paid',
                'reservation_fee' => 600,
                'paid_amount' => 600,
                'remaining_balance' => 0,
                'cancellation_policy' => 'A 50% cancellation fee will be deducted upon cancellation. The remaining balance will be refunded.',
                'cancellation_allowed' => true,
            ],
            [
                'id' => 'RES-2026-780',
                'cafe_slug' => 'the-velvet-bean',
                'cafe_name' => 'The Velvet Bean',
                'cafe_location' => 'Colombo 07',
                'cafe_image' => 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=400&q=80',
                'date' => 'Sun, Sep 28, 2026',
                'time' => '4:30 PM',
                'guests' => 2,
                'table_name' => 'Table 3',
                'table_type' => 'Rooftop Lounge',
                'table_location' => 'Rooftop',
                'status' => 'completed',
                'status_label' => 'Completed',
                'payment_status' => 'Paid',
                'reservation_fee' => 500,
                'paid_amount' => 500,
                'remaining_balance' => 0,
                'cancellation_policy' => 'Reservation completed successfully.',
                'cancellation_allowed' => false,
            ],
            [
                'id' => 'RES-2026-752',
                'cafe_slug' => 'the-daily-grind',
                'cafe_name' => 'The Daily Grind',
                'cafe_location' => 'Colombo 03',
                'cafe_image' => 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=400&q=80',
                'date' => 'Sun, Sep 14, 2026',
                'time' => '3:00 PM',
                'guests' => 4,
                'table_name' => 'Table 2',
                'table_type' => 'Library Nook',
                'table_location' => 'Indoor',
                'status' => 'cancelled',
                'status_label' => 'Cancelled',
                'payment_status' => 'Refunded (50%)',
                'reservation_fee' => 350,
                'paid_amount' => 350,
                'remaining_balance' => 0,
                'cancellation_policy' => 'Cancelled with 50% fee deducted. Remaining 50% refunded to payment card.',
                'cancellation_allowed' => false,
            ],
        ];
    }
}
